### ISSUE TITLE
Apply social login (OAuth)

### ISSUE THREAD

**Issue by Alejandroacho** [Alejandroacho/BackendTemplate#15]
## 📄 Description
For a more usable and global usage of the app, OAuth is needed. Is needed in order to allow register and log in with social media.

## ☑ ToDo
- [x] Implement OAtuh.
- [x] Add facebook support.
- [x] Add google support.
- [x] Add apple support.
- [x] Add twitter support.
