### ISSUE TITLE
Add email endpoints

### ISSUE THREAD

**Issue by Alejandroacho** [Alejandroacho/BackendTemplate#28]
## 📄 Description
We want to achieve 2 main points with this issue.

### 1-. Enable user customization.
We want to allow users to set their preferences on which type of emails they want to receive. In order to do that, we have to add "type" to email models. Then we have to create endpoints in order to allow them to CRUD their preferences.

### 2-. Enable email sender API.
We want to be able to send emails through an API as an admin user. We want to enable the API creation for `Notifications` and `Email`.

## ☑️ ToDo
- [x] Add "type" to emails models.
- [x] Refactor tests and code according new changes.
- [x] Create if not exists permission to use with `BlackList`.
- [x] Create `BlackList` tested endpoints.
- [x] Create `Notification` tested endpoints.
- [x] Create `Email` tested endpoints.
