### ISSUE TITLE
Add command params to a file

### ISSUE THREAD

**Issue by Alejandroacho** [Alejandroacho/BackendTemplate#29]
## 📄 Description
In order to apply [PEP 518](https://peps.python.org/pep-0518/), we should use TOML files to have there the configuration on the commands we usually use. As we are using a lot the commands to check format and imports order (for dev, in pre-commit hook and in the CI workflow), we should centralize its configuration in a TOML file.

## ☑️ ToDo
- [ ] Add to TOML file the lint configuration.
- [ ] Add to TOML file the imports configuration.
- [ ] Change if needed CI workflow.
- [ ] Change if needed pre-commit hook.
