### ISSUE TITLE
Change project folder structure

### ISSUE THREAD

**Issue by Alejandroacho** [Alejandroacho/BackendTemplate#42]
## 📄 Description
In order to have a more readable folder structure, we want to refactor it in order to separate the apps from the project settings files. To achieve that, a full refactor in structure and files is needed.
## ☑️ ToDo
- [ ] Separate apps from project settings.
- [ ] Rename `App` folder to `Apps`.
- [ ] Fix broken features.
