### ISSUE TITLE
Refactor email

### ISSUE THREAD

**Issue by Alejandroacho** [Alejandroacho/BackendTemplate#8]
## 📄  Description
The email was planning at the beginning to be user-agnostic, but after re-thinking the idea to keep track on which emails a user has received, it would be great to have the relation between user and email.

Also, in order to make an historic track of conversations, it would be nice to have a `ReplyEmail` for the `Suggestion` model in order to be able to show the entire conversation to the user.

## ☑️ ToDo
- [ ] Apply the relation with `User` to the `Email` model.
- [ ] Implement a `SuggestionReply` model related to suggestions.
- [ ] Create a way to be able to have "global emails" and "emails for non-users".
